version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: oxcaml-icfp-tutorial:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity